language: scala
dist: xenial
jdk: openjdk8
matrix:
  include:
  - env: SBT_VERSION="0.13.18"
  - env: SBT_VERSION="1.1.6"
  - env: SBT_VERSION="1.3.3"
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk11
script:
 - git config --global user.email "example@example.com"
 - git config --global user.name "example"
 - echo '[ui]' > "$HOME/.hgrc"
 - echo 'username = example <example@example.com>' >> "$HOME/.hgrc"
 - sbt "^^ ${SBT_VERSION}" test scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
sudo: false
